version: '3.1'
services:
  elite2-web:
    image: sysconjusticesystems/elite2-web:demo-latest
    networks:
      - azure
    depends_on:
      - elite2-api
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == worker]
    environment:
      - PORT=3000
      - API_ENDPOINT_URL=http://elite2-api:8080/api/
      - USE_API_GATEWAY_AUTH=no
      - GOOGLE_ANALYTICS_ID=UA-106741063-1
      - WEB_SESSION_TIMEOUT_IN_MINUTES=20
      - NOMS_TOKEN=secret_token

  elite2-api:
    image: sysconjusticesystems/elite2-api:latest
    networks:
      - azure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/info/health"]
    deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == worker]
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis,nomis-hsqldb,noproxy
      - JWT_EXPIRATION_MINS=5
      - JWT_REFRESH_EXPIRATION_MINS=25
networks:
  azure:
