version: '3.1'
services:
  elite2-web:
    image: sysconjusticesystems/elite2-web:latest
    container_name: elite2-web
    depends_on:
      - elite2-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_ENDPOINT_URL=http://elite2-api:8080/api/
      - USE_API_GATEWAY_AUTH=no
      - NOMS_TOKEN=amagictoken

  elite2-api:
    image: sysconjusticesystems/elite2-api:latest
    container_name: elite2-api
    ports:
      - "7080:8080"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx128m
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis,nomis-hsqldb,noproxy,dev