defaults: &defaults
  working_directory: /tmp/circleci-elite2-web
  docker:
    - image: circleci/node:latest-browsers
      environment:
        BUILD_NUMBER: $(eval echo "$CIRCLE_BRANCH-$CIRCLE_SHA1")
        GIT_REF: $CIRCLE_SHA1
        GIT_DATE: $(TZ=UTC git log --format=%cd -n1 --date=iso-strict-local $CIRCLE_SHA1)

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            export CURRENT_BUILD_NO=$(eval echo $BUILD_NUMBER)
            echo Building : $CURRENT_BUILD_NO
      - run: yarn --frozen-lockfile
      - run: yarn test -- --reporter mocha-junit-reporter
      - persist_to_workspace:
          root: .

  prod_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/circleci-elite2-web
      - run: export BUILD_NUMBER=$(eval echo $BUILD_NUMBER)
      - run: NODE_ENV=production yarn build
      - run: yarn record-build-info
      - persist_to_workspace:
          root: .

  build_docker:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/circleci-elite2-web
      - setup_remote_docker:
          exclusive: true
      - run:
          command: |
             export CURRENT_BUILD_NO=$(eval echo $BUILD_NUMBER)
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker build --rm=false -t sysconjusticesystems/elite2-web:$CURRENT_BUILD_NO .
             docker push sysconjusticesystems/elite2-web

  tag_latest_image:
    <<: *defaults
    steps:
      - setup_remote_docker:
          exclusive: true
      - run:
          command: |
             export CURRENT_BUILD_NO=$(eval echo $BUILD_NUMBER)
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker pull sysconjusticesystems/elite2-web:$CURRENT_BUILD_NO
             docker tag sysconjusticesystems/elite2-web:$CURRENT_BUILD_NO sysconjusticesystems/elite2-web:latest
             docker push sysconjusticesystems/elite2-web:latest

  commit_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/circleci-elite2-web
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
            git add --force --verbose build-info.json build
            git config user.name "Circle CI"
            git config user.email "circle@circleci.com"
            CI_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            CURRENT_BUILD_NO=$(eval echo $BUILD_NUMBER)
            git commit -m "Deployment of build $CURRENT_BUILD_NO" -m "$CI_MESSAGE" -m "From gitref $CIRCLE_SHA1"
            git push --force origin HEAD:deploy-to-mock

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: deploy-to-mock
      - prod_build:
          filters:
            branches:
              only: master
          requires:
            - build
      - build_docker:
          requires:
            - build
      - commit_build:
          filters:
            branches:
              only: master
          requires:
            - prod_build
      - tag_latest_image:
          filters:
            branches:
              only: master
          requires:
            - build_docker