---
# Serves as base route for all api calls to Elite.
# apiServer: http://notm-dev.azurewebsites.net/api/
apiServer: http://207.230.255.121:8080/api/

# What users should be able to search on, and their titles.
# Ordering will stay the same.
bookingSearchOptions:
  - firstName:
      title: First Name / Alias
  - lastName:
      title: Last Name
  - offenderId:
      title: 'NOMS #'
  - bookingId:
      title: 'Booking #'
  - assignedLivingUnitId:
      title: Location
# assignedOfficerUserId:
# agencyId:
# currentLocationId:
# inmateId:
# offenderId:
#
#
