---

# What users should be able to search on, and their titles.
# Ordering will stay the same.
bookingSearchOptions:
  - firstName:
      title: First Name / Alias
  - lastName:
      title: Last Name
  - offenderId:
      title: 'NOMS #'
  - bookingId:
      title: 'Booking #'
  - assignedLivingUnitId:
      title: Location
# assignedOfficerUserId:
# agencyId:
# currentLocationId:
# inmateId:
# offenderId:
#
#
